// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tensorflow_serving/apis/logging.proto
// Protobuf Java Version: 4.27.3

package tensorflow.serving;

public final class Logging {
  private Logging() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      Logging.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.LogMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     * @return Whether the modelSpec field is set.
     */
    boolean hasModelSpec();
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     * @return The modelSpec.
     */
    tensorflow.serving.Model.ModelSpec getModelSpec();
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    tensorflow.serving.Model.ModelSpecOrBuilder getModelSpecOrBuilder();

    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     * @return Whether the samplingConfig field is set.
     */
    boolean hasSamplingConfig();
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     * @return The samplingConfig.
     */
    tensorflow.serving.LoggingConfigOuterClass.SamplingConfig getSamplingConfig();
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder();

    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @return A list containing the savedModelTags.
     */
    java.util.List<java.lang.String>
        getSavedModelTagsList();
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @return The count of savedModelTags.
     */
    int getSavedModelTagsCount();
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @param index The index of the element to return.
     * @return The savedModelTags at the given index.
     */
    java.lang.String getSavedModelTags(int index);
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the savedModelTags at the given index.
     */
    com.google.protobuf.ByteString
        getSavedModelTagsBytes(int index);

    /**
     * <pre>
     * Seconds since epoch.
     * </pre>
     *
     * <code>int64 timestamp_secs = 4;</code>
     * @return The timestampSecs.
     */
    long getTimestampSecs();

    /**
     * <pre>
     * Datacenter where the request was logged.
     * </pre>
     *
     * <code>string dc = 5;</code>
     * @return The dc.
     */
    java.lang.String getDc();
    /**
     * <pre>
     * Datacenter where the request was logged.
     * </pre>
     *
     * <code>string dc = 5;</code>
     * @return The bytes for dc.
     */
    com.google.protobuf.ByteString
        getDcBytes();

    /**
     * <pre>
     * Request origin identifier.
     * </pre>
     *
     * <code>string request_origin = 6;</code>
     * @return The requestOrigin.
     */
    java.lang.String getRequestOrigin();
    /**
     * <pre>
     * Request origin identifier.
     * </pre>
     *
     * <code>string request_origin = 6;</code>
     * @return The bytes for requestOrigin.
     */
    com.google.protobuf.ByteString
        getRequestOriginBytes();

    /**
     * <pre>
     * Request QoS.
     * </pre>
     *
     * <code>string request_criticality = 7;</code>
     * @return The requestCriticality.
     */
    java.lang.String getRequestCriticality();
    /**
     * <pre>
     * Request QoS.
     * </pre>
     *
     * <code>string request_criticality = 7;</code>
     * @return The bytes for requestCriticality.
     */
    com.google.protobuf.ByteString
        getRequestCriticalityBytes();
  }
  /**
   * <pre>
   * Metadata logged along with the request logs.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.LogMetadata}
   */
  public static final class LogMetadata extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.LogMetadata)
      LogMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        LogMetadata.class.getName());
    }
    // Use LogMetadata.newBuilder() to construct.
    private LogMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LogMetadata() {
      savedModelTags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      dc_ = "";
      requestOrigin_ = "";
      requestCriticality_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.serving.Logging.LogMetadata.class, tensorflow.serving.Logging.LogMetadata.Builder.class);
    }

    private int bitField0_;
    public static final int MODEL_SPEC_FIELD_NUMBER = 1;
    private tensorflow.serving.Model.ModelSpec modelSpec_;
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     * @return Whether the modelSpec field is set.
     */
    @java.lang.Override
    public boolean hasModelSpec() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     * @return The modelSpec.
     */
    @java.lang.Override
    public tensorflow.serving.Model.ModelSpec getModelSpec() {
      return modelSpec_ == null ? tensorflow.serving.Model.ModelSpec.getDefaultInstance() : modelSpec_;
    }
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    @java.lang.Override
    public tensorflow.serving.Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
      return modelSpec_ == null ? tensorflow.serving.Model.ModelSpec.getDefaultInstance() : modelSpec_;
    }

    public static final int SAMPLING_CONFIG_FIELD_NUMBER = 2;
    private tensorflow.serving.LoggingConfigOuterClass.SamplingConfig samplingConfig_;
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     * @return Whether the samplingConfig field is set.
     */
    @java.lang.Override
    public boolean hasSamplingConfig() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     * @return The samplingConfig.
     */
    @java.lang.Override
    public tensorflow.serving.LoggingConfigOuterClass.SamplingConfig getSamplingConfig() {
      return samplingConfig_ == null ? tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
    }
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    @java.lang.Override
    public tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
      return samplingConfig_ == null ? tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
    }

    public static final int SAVED_MODEL_TAGS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList savedModelTags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @return A list containing the savedModelTags.
     */
    public com.google.protobuf.ProtocolStringList
        getSavedModelTagsList() {
      return savedModelTags_;
    }
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @return The count of savedModelTags.
     */
    public int getSavedModelTagsCount() {
      return savedModelTags_.size();
    }
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @param index The index of the element to return.
     * @return The savedModelTags at the given index.
     */
    public java.lang.String getSavedModelTags(int index) {
      return savedModelTags_.get(index);
    }
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the savedModelTags at the given index.
     */
    public com.google.protobuf.ByteString
        getSavedModelTagsBytes(int index) {
      return savedModelTags_.getByteString(index);
    }

    public static final int TIMESTAMP_SECS_FIELD_NUMBER = 4;
    private long timestampSecs_ = 0L;
    /**
     * <pre>
     * Seconds since epoch.
     * </pre>
     *
     * <code>int64 timestamp_secs = 4;</code>
     * @return The timestampSecs.
     */
    @java.lang.Override
    public long getTimestampSecs() {
      return timestampSecs_;
    }

    public static final int DC_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dc_ = "";
    /**
     * <pre>
     * Datacenter where the request was logged.
     * </pre>
     *
     * <code>string dc = 5;</code>
     * @return The dc.
     */
    @java.lang.Override
    public java.lang.String getDc() {
      java.lang.Object ref = dc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dc_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Datacenter where the request was logged.
     * </pre>
     *
     * <code>string dc = 5;</code>
     * @return The bytes for dc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDcBytes() {
      java.lang.Object ref = dc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_ORIGIN_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestOrigin_ = "";
    /**
     * <pre>
     * Request origin identifier.
     * </pre>
     *
     * <code>string request_origin = 6;</code>
     * @return The requestOrigin.
     */
    @java.lang.Override
    public java.lang.String getRequestOrigin() {
      java.lang.Object ref = requestOrigin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestOrigin_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Request origin identifier.
     * </pre>
     *
     * <code>string request_origin = 6;</code>
     * @return The bytes for requestOrigin.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestOriginBytes() {
      java.lang.Object ref = requestOrigin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestOrigin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_CRITICALITY_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestCriticality_ = "";
    /**
     * <pre>
     * Request QoS.
     * </pre>
     *
     * <code>string request_criticality = 7;</code>
     * @return The requestCriticality.
     */
    @java.lang.Override
    public java.lang.String getRequestCriticality() {
      java.lang.Object ref = requestCriticality_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestCriticality_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Request QoS.
     * </pre>
     *
     * <code>string request_criticality = 7;</code>
     * @return The bytes for requestCriticality.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestCriticalityBytes() {
      java.lang.Object ref = requestCriticality_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestCriticality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getModelSpec());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getSamplingConfig());
      }
      for (int i = 0; i < savedModelTags_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, savedModelTags_.getRaw(i));
      }
      if (timestampSecs_ != 0L) {
        output.writeInt64(4, timestampSecs_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dc_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, dc_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestOrigin_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, requestOrigin_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestCriticality_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, requestCriticality_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getModelSpec());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSamplingConfig());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < savedModelTags_.size(); i++) {
          dataSize += computeStringSizeNoTag(savedModelTags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSavedModelTagsList().size();
      }
      if (timestampSecs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestampSecs_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dc_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, dc_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestOrigin_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, requestOrigin_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestCriticality_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, requestCriticality_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tensorflow.serving.Logging.LogMetadata)) {
        return super.equals(obj);
      }
      tensorflow.serving.Logging.LogMetadata other = (tensorflow.serving.Logging.LogMetadata) obj;

      if (hasModelSpec() != other.hasModelSpec()) return false;
      if (hasModelSpec()) {
        if (!getModelSpec()
            .equals(other.getModelSpec())) return false;
      }
      if (hasSamplingConfig() != other.hasSamplingConfig()) return false;
      if (hasSamplingConfig()) {
        if (!getSamplingConfig()
            .equals(other.getSamplingConfig())) return false;
      }
      if (!getSavedModelTagsList()
          .equals(other.getSavedModelTagsList())) return false;
      if (getTimestampSecs()
          != other.getTimestampSecs()) return false;
      if (!getDc()
          .equals(other.getDc())) return false;
      if (!getRequestOrigin()
          .equals(other.getRequestOrigin())) return false;
      if (!getRequestCriticality()
          .equals(other.getRequestCriticality())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModelSpec()) {
        hash = (37 * hash) + MODEL_SPEC_FIELD_NUMBER;
        hash = (53 * hash) + getModelSpec().hashCode();
      }
      if (hasSamplingConfig()) {
        hash = (37 * hash) + SAMPLING_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getSamplingConfig().hashCode();
      }
      if (getSavedModelTagsCount() > 0) {
        hash = (37 * hash) + SAVED_MODEL_TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getSavedModelTagsList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_SECS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampSecs());
      hash = (37 * hash) + DC_FIELD_NUMBER;
      hash = (53 * hash) + getDc().hashCode();
      hash = (37 * hash) + REQUEST_ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getRequestOrigin().hashCode();
      hash = (37 * hash) + REQUEST_CRITICALITY_FIELD_NUMBER;
      hash = (53 * hash) + getRequestCriticality().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static tensorflow.serving.Logging.LogMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static tensorflow.serving.Logging.LogMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.serving.Logging.LogMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Metadata logged along with the request logs.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.LogMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.LogMetadata)
        tensorflow.serving.Logging.LogMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.serving.Logging.LogMetadata.class, tensorflow.serving.Logging.LogMetadata.Builder.class);
      }

      // Construct using tensorflow.serving.Logging.LogMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getModelSpecFieldBuilder();
          getSamplingConfigFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        modelSpec_ = null;
        if (modelSpecBuilder_ != null) {
          modelSpecBuilder_.dispose();
          modelSpecBuilder_ = null;
        }
        samplingConfig_ = null;
        if (samplingConfigBuilder_ != null) {
          samplingConfigBuilder_.dispose();
          samplingConfigBuilder_ = null;
        }
        savedModelTags_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        timestampSecs_ = 0L;
        dc_ = "";
        requestOrigin_ = "";
        requestCriticality_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_descriptor;
      }

      @java.lang.Override
      public tensorflow.serving.Logging.LogMetadata getDefaultInstanceForType() {
        return tensorflow.serving.Logging.LogMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public tensorflow.serving.Logging.LogMetadata build() {
        tensorflow.serving.Logging.LogMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tensorflow.serving.Logging.LogMetadata buildPartial() {
        tensorflow.serving.Logging.LogMetadata result = new tensorflow.serving.Logging.LogMetadata(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(tensorflow.serving.Logging.LogMetadata result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.modelSpec_ = modelSpecBuilder_ == null
              ? modelSpec_
              : modelSpecBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.samplingConfig_ = samplingConfigBuilder_ == null
              ? samplingConfig_
              : samplingConfigBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          savedModelTags_.makeImmutable();
          result.savedModelTags_ = savedModelTags_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.timestampSecs_ = timestampSecs_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.dc_ = dc_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.requestOrigin_ = requestOrigin_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.requestCriticality_ = requestCriticality_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.serving.Logging.LogMetadata) {
          return mergeFrom((tensorflow.serving.Logging.LogMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.serving.Logging.LogMetadata other) {
        if (other == tensorflow.serving.Logging.LogMetadata.getDefaultInstance()) return this;
        if (other.hasModelSpec()) {
          mergeModelSpec(other.getModelSpec());
        }
        if (other.hasSamplingConfig()) {
          mergeSamplingConfig(other.getSamplingConfig());
        }
        if (!other.savedModelTags_.isEmpty()) {
          if (savedModelTags_.isEmpty()) {
            savedModelTags_ = other.savedModelTags_;
            bitField0_ |= 0x00000004;
          } else {
            ensureSavedModelTagsIsMutable();
            savedModelTags_.addAll(other.savedModelTags_);
          }
          onChanged();
        }
        if (other.getTimestampSecs() != 0L) {
          setTimestampSecs(other.getTimestampSecs());
        }
        if (!other.getDc().isEmpty()) {
          dc_ = other.dc_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getRequestOrigin().isEmpty()) {
          requestOrigin_ = other.requestOrigin_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getRequestCriticality().isEmpty()) {
          requestCriticality_ = other.requestCriticality_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getModelSpecFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getSamplingConfigFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureSavedModelTagsIsMutable();
                savedModelTags_.add(s);
                break;
              } // case 26
              case 32: {
                timestampSecs_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                dc_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                requestOrigin_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                requestCriticality_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private tensorflow.serving.Model.ModelSpec modelSpec_;
      private com.google.protobuf.SingleFieldBuilder<
          tensorflow.serving.Model.ModelSpec, tensorflow.serving.Model.ModelSpec.Builder, tensorflow.serving.Model.ModelSpecOrBuilder> modelSpecBuilder_;
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       * @return Whether the modelSpec field is set.
       */
      public boolean hasModelSpec() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       * @return The modelSpec.
       */
      public tensorflow.serving.Model.ModelSpec getModelSpec() {
        if (modelSpecBuilder_ == null) {
          return modelSpec_ == null ? tensorflow.serving.Model.ModelSpec.getDefaultInstance() : modelSpec_;
        } else {
          return modelSpecBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(tensorflow.serving.Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modelSpec_ = value;
        } else {
          modelSpecBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(
          tensorflow.serving.Model.ModelSpec.Builder builderForValue) {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = builderForValue.build();
        } else {
          modelSpecBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder mergeModelSpec(tensorflow.serving.Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            modelSpec_ != null &&
            modelSpec_ != tensorflow.serving.Model.ModelSpec.getDefaultInstance()) {
            getModelSpecBuilder().mergeFrom(value);
          } else {
            modelSpec_ = value;
          }
        } else {
          modelSpecBuilder_.mergeFrom(value);
        }
        if (modelSpec_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder clearModelSpec() {
        bitField0_ = (bitField0_ & ~0x00000001);
        modelSpec_ = null;
        if (modelSpecBuilder_ != null) {
          modelSpecBuilder_.dispose();
          modelSpecBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public tensorflow.serving.Model.ModelSpec.Builder getModelSpecBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getModelSpecFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public tensorflow.serving.Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
        if (modelSpecBuilder_ != null) {
          return modelSpecBuilder_.getMessageOrBuilder();
        } else {
          return modelSpec_ == null ?
              tensorflow.serving.Model.ModelSpec.getDefaultInstance() : modelSpec_;
        }
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tensorflow.serving.Model.ModelSpec, tensorflow.serving.Model.ModelSpec.Builder, tensorflow.serving.Model.ModelSpecOrBuilder> 
          getModelSpecFieldBuilder() {
        if (modelSpecBuilder_ == null) {
          modelSpecBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tensorflow.serving.Model.ModelSpec, tensorflow.serving.Model.ModelSpec.Builder, tensorflow.serving.Model.ModelSpecOrBuilder>(
                  getModelSpec(),
                  getParentForChildren(),
                  isClean());
          modelSpec_ = null;
        }
        return modelSpecBuilder_;
      }

      private tensorflow.serving.LoggingConfigOuterClass.SamplingConfig samplingConfig_;
      private com.google.protobuf.SingleFieldBuilder<
          tensorflow.serving.LoggingConfigOuterClass.SamplingConfig, tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder, tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder> samplingConfigBuilder_;
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       * @return Whether the samplingConfig field is set.
       */
      public boolean hasSamplingConfig() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       * @return The samplingConfig.
       */
      public tensorflow.serving.LoggingConfigOuterClass.SamplingConfig getSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          return samplingConfig_ == null ? tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
        } else {
          return samplingConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(tensorflow.serving.LoggingConfigOuterClass.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          samplingConfig_ = value;
        } else {
          samplingConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(
          tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder builderForValue) {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = builderForValue.build();
        } else {
          samplingConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder mergeSamplingConfig(tensorflow.serving.LoggingConfigOuterClass.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            samplingConfig_ != null &&
            samplingConfig_ != tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.getDefaultInstance()) {
            getSamplingConfigBuilder().mergeFrom(value);
          } else {
            samplingConfig_ = value;
          }
        } else {
          samplingConfigBuilder_.mergeFrom(value);
        }
        if (samplingConfig_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder clearSamplingConfig() {
        bitField0_ = (bitField0_ & ~0x00000002);
        samplingConfig_ = null;
        if (samplingConfigBuilder_ != null) {
          samplingConfigBuilder_.dispose();
          samplingConfigBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder getSamplingConfigBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSamplingConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
        if (samplingConfigBuilder_ != null) {
          return samplingConfigBuilder_.getMessageOrBuilder();
        } else {
          return samplingConfig_ == null ?
              tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
        }
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tensorflow.serving.LoggingConfigOuterClass.SamplingConfig, tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder, tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder> 
          getSamplingConfigFieldBuilder() {
        if (samplingConfigBuilder_ == null) {
          samplingConfigBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tensorflow.serving.LoggingConfigOuterClass.SamplingConfig, tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder, tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder>(
                  getSamplingConfig(),
                  getParentForChildren(),
                  isClean());
          samplingConfig_ = null;
        }
        return samplingConfigBuilder_;
      }

      private com.google.protobuf.LazyStringArrayList savedModelTags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureSavedModelTagsIsMutable() {
        if (!savedModelTags_.isModifiable()) {
          savedModelTags_ = new com.google.protobuf.LazyStringArrayList(savedModelTags_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @return A list containing the savedModelTags.
       */
      public com.google.protobuf.ProtocolStringList
          getSavedModelTagsList() {
        savedModelTags_.makeImmutable();
        return savedModelTags_;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @return The count of savedModelTags.
       */
      public int getSavedModelTagsCount() {
        return savedModelTags_.size();
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param index The index of the element to return.
       * @return The savedModelTags at the given index.
       */
      public java.lang.String getSavedModelTags(int index) {
        return savedModelTags_.get(index);
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the savedModelTags at the given index.
       */
      public com.google.protobuf.ByteString
          getSavedModelTagsBytes(int index) {
        return savedModelTags_.getByteString(index);
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param index The index to set the value at.
       * @param value The savedModelTags to set.
       * @return This builder for chaining.
       */
      public Builder setSavedModelTags(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSavedModelTagsIsMutable();
        savedModelTags_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param value The savedModelTags to add.
       * @return This builder for chaining.
       */
      public Builder addSavedModelTags(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSavedModelTagsIsMutable();
        savedModelTags_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param values The savedModelTags to add.
       * @return This builder for chaining.
       */
      public Builder addAllSavedModelTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureSavedModelTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, savedModelTags_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSavedModelTags() {
        savedModelTags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param value The bytes of the savedModelTags to add.
       * @return This builder for chaining.
       */
      public Builder addSavedModelTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureSavedModelTagsIsMutable();
        savedModelTags_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long timestampSecs_ ;
      /**
       * <pre>
       * Seconds since epoch.
       * </pre>
       *
       * <code>int64 timestamp_secs = 4;</code>
       * @return The timestampSecs.
       */
      @java.lang.Override
      public long getTimestampSecs() {
        return timestampSecs_;
      }
      /**
       * <pre>
       * Seconds since epoch.
       * </pre>
       *
       * <code>int64 timestamp_secs = 4;</code>
       * @param value The timestampSecs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampSecs(long value) {

        timestampSecs_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Seconds since epoch.
       * </pre>
       *
       * <code>int64 timestamp_secs = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampSecs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestampSecs_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object dc_ = "";
      /**
       * <pre>
       * Datacenter where the request was logged.
       * </pre>
       *
       * <code>string dc = 5;</code>
       * @return The dc.
       */
      public java.lang.String getDc() {
        java.lang.Object ref = dc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Datacenter where the request was logged.
       * </pre>
       *
       * <code>string dc = 5;</code>
       * @return The bytes for dc.
       */
      public com.google.protobuf.ByteString
          getDcBytes() {
        java.lang.Object ref = dc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Datacenter where the request was logged.
       * </pre>
       *
       * <code>string dc = 5;</code>
       * @param value The dc to set.
       * @return This builder for chaining.
       */
      public Builder setDc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dc_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Datacenter where the request was logged.
       * </pre>
       *
       * <code>string dc = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDc() {
        dc_ = getDefaultInstance().getDc();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Datacenter where the request was logged.
       * </pre>
       *
       * <code>string dc = 5;</code>
       * @param value The bytes for dc to set.
       * @return This builder for chaining.
       */
      public Builder setDcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dc_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object requestOrigin_ = "";
      /**
       * <pre>
       * Request origin identifier.
       * </pre>
       *
       * <code>string request_origin = 6;</code>
       * @return The requestOrigin.
       */
      public java.lang.String getRequestOrigin() {
        java.lang.Object ref = requestOrigin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestOrigin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Request origin identifier.
       * </pre>
       *
       * <code>string request_origin = 6;</code>
       * @return The bytes for requestOrigin.
       */
      public com.google.protobuf.ByteString
          getRequestOriginBytes() {
        java.lang.Object ref = requestOrigin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestOrigin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Request origin identifier.
       * </pre>
       *
       * <code>string request_origin = 6;</code>
       * @param value The requestOrigin to set.
       * @return This builder for chaining.
       */
      public Builder setRequestOrigin(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestOrigin_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Request origin identifier.
       * </pre>
       *
       * <code>string request_origin = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestOrigin() {
        requestOrigin_ = getDefaultInstance().getRequestOrigin();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Request origin identifier.
       * </pre>
       *
       * <code>string request_origin = 6;</code>
       * @param value The bytes for requestOrigin to set.
       * @return This builder for chaining.
       */
      public Builder setRequestOriginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestOrigin_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object requestCriticality_ = "";
      /**
       * <pre>
       * Request QoS.
       * </pre>
       *
       * <code>string request_criticality = 7;</code>
       * @return The requestCriticality.
       */
      public java.lang.String getRequestCriticality() {
        java.lang.Object ref = requestCriticality_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestCriticality_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Request QoS.
       * </pre>
       *
       * <code>string request_criticality = 7;</code>
       * @return The bytes for requestCriticality.
       */
      public com.google.protobuf.ByteString
          getRequestCriticalityBytes() {
        java.lang.Object ref = requestCriticality_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestCriticality_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Request QoS.
       * </pre>
       *
       * <code>string request_criticality = 7;</code>
       * @param value The requestCriticality to set.
       * @return This builder for chaining.
       */
      public Builder setRequestCriticality(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestCriticality_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Request QoS.
       * </pre>
       *
       * <code>string request_criticality = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestCriticality() {
        requestCriticality_ = getDefaultInstance().getRequestCriticality();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Request QoS.
       * </pre>
       *
       * <code>string request_criticality = 7;</code>
       * @param value The bytes for requestCriticality to set.
       * @return This builder for chaining.
       */
      public Builder setRequestCriticalityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestCriticality_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tensorflow.serving.LogMetadata)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.LogMetadata)
    private static final tensorflow.serving.Logging.LogMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.serving.Logging.LogMetadata();
    }

    public static tensorflow.serving.Logging.LogMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogMetadata>
        PARSER = new com.google.protobuf.AbstractParser<LogMetadata>() {
      @java.lang.Override
      public LogMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LogMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tensorflow.serving.Logging.LogMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_LogMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_serving_LogMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%tensorflow_serving/apis/logging.proto\022" +
      "\022tensorflow.serving\032#tensorflow_serving/" +
      "apis/model.proto\032.tensorflow_serving/con" +
      "fig/logging_config.proto\"\360\001\n\013LogMetadata" +
      "\0221\n\nmodel_spec\030\001 \001(\0132\035.tensorflow.servin" +
      "g.ModelSpec\022;\n\017sampling_config\030\002 \001(\0132\".t" +
      "ensorflow.serving.SamplingConfig\022\030\n\020save" +
      "d_model_tags\030\003 \003(\t\022\026\n\016timestamp_secs\030\004 \001" +
      "(\003\022\n\n\002dc\030\005 \001(\t\022\026\n\016request_origin\030\006 \001(\t\022\033" +
      "\n\023request_criticality\030\007 \001(\tB\003\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tensorflow.serving.Model.getDescriptor(),
          tensorflow.serving.LoggingConfigOuterClass.getDescriptor(),
        });
    internal_static_tensorflow_serving_LogMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_LogMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_serving_LogMetadata_descriptor,
        new java.lang.String[] { "ModelSpec", "SamplingConfig", "SavedModelTags", "TimestampSecs", "Dc", "RequestOrigin", "RequestCriticality", });
    descriptor.resolveAllFeaturesImmutable();
    tensorflow.serving.Model.getDescriptor();
    tensorflow.serving.LoggingConfigOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
